Vagrant.configure('2') do |config|
  config.vm.box = 'unaboxdummy'
  config.ssh.private_key_path = '~/.ssh/id_rsa'
  config.vm.provider :azure do |azure, override|
    azure.tenant_id = ENV['AZURE_TENANT_ID']
    azure.client_id = ENV['AZURE_CLIENT_ID']
    azure.client_secret = ENV['AZURE_CLIENT_SECRET']
    azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
    azure.resource_group_name = "CCGroup"
    azure.location = "uksouth"
    azure.vm_size = "Standard_B1s"
    azure.vm_image_urn = "Canonical:UbuntuServer:16.04-LTS:16.04.201812070"
    azure.tcp_endpoints = [22, 80]
  end
  config.vm.define "info" do |info|
    config.vm.provider :azure do |azureinfo, override|
      azureinfo.vm_name = "info"
      azureinfo.dns_name = "ccazureinfo"
      azureinfo.data_disks = [
         {
           name: "discoinfo", 
           size_gb: 1
         }
      ]
    end
  end
  config.vm.define "viajes" do |viajes|
    config.vm.provider :azure do |azureviajes, override|
      azureviajes.vm_name = "viajes"
      azureviajes.dns_name = "ccazureviajes"
      azureviajes.data_disks = [
         {
           name: "discoviajes", 
           size_gb: 1
         }
      ]
    end
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.inventory_path = "/etc/ansible/hosts"
      ansible.limit = "all"
    end
  end
end
